[project]
name = "Enterprise_RAG_Example"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "docling>=2.25.1",
    "ocrmac>=1.0.0",
    "chonkie>=0.5.1",
    "tiktoken>=0.9.0",
    "sentence-transformers>=3.4.1",
    "elasticsearch>=8.0.0"
]


